name: Nix Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.rs"
      - ".github/workflows/nix-build.yml"
      - "nix/**"
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - ".github/workflows/nix-build.yml"
      - "nix/**"

jobs:
  lints:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: baalajimaestro
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --json | jq -r '.[].outputs | to_entries[].value' | cachix push baalajimaestro
