name: Nix Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '.github/workflows/nix-build.yml'
      - 'nix/**'
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '.github/workflows/nix-build.yml'
      - 'nix/**'

jobs:
  lints:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - uses: DeterminateSystems/flake-checker-action@main
      
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: baalajimaestro
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          
      - name: Build and push to Cachix
        run: |
          nix build --max-jobs auto --build-max-jobs auto --print-build-logs | cachix push baalajimaestro